# Go API Gateway Configuration
# This file is used by the Go API Gateway service

server:
  port: 8000
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  shutdown_timeout: "10s"
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"
      - "http://localhost"
      - "http://erp-frontend:3000"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
      - "PATCH"
    allowed_headers:
      - "Authorization"
      - "Content-Type"
      - "X-Requested-With"
      - "Accept"
      - "Origin"
    allow_credentials: true
    max_age: 86400

database:
  host: "postgres"
  port: 5432
  name: "erp_gateway"
  user: "postgres"
  password: "postgres"
  ssl_mode: "disable"

redis:
  host: "redis"
  port: 6379
  password: "redispassword"
  db: 1
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"

kafka:
  brokers:
    - "localhost:9092"
  client_id: "go-api-gateway"
  retry_max: 3
  retry_backoff: "100ms"
  flush_messages: 100
  flush_bytes: 1048576  # 1MB
  flush_timeout: "1s"
  enabled: true

grpc:
  auth_service:
    host: "auth-service"
    port: 50051
    timeout: "10s"
    max_retries: 3
    retry_backoff: "100ms"
    circuit_breaker:
      max_failures: 5
      timeout: "60s"
      interval: "10s"
  ai_copilot_service:
    host: "ai-copilot"
    port: 50051
    timeout: "30s"
    max_retries: 3
    retry_backoff: "100ms"
    circuit_breaker:
      max_failures: 5
      timeout: "60s"
      interval: "10s"

# GraphQL Configuration (Local Handler)
graphql:
  enable_playground: true
  enable_introspection: true
  timeout: "30s"

# WebSocket Configuration (Proxies to AI Service)
websocket:
  server_host: "erp-suite-ai-copilot"  # Host where AI Copilot service is running in Docker network
  server_port: 8003          # AI Copilot service port
  endpoint: "/ws"            # AI Copilot WebSocket endpoint (base path)
  enable_cors: true
  timeout: "30s"
  read_buffer_size: 4096
  write_buffer_size: 4096
  handshake_timeout: "10s"
  read_timeout: "60s"
  write_timeout: "10s"
  pong_timeout: "60s"
  ping_period: "54s"
  max_message_size: 1048576  # 1MB
  max_connections: 10000
  allowed_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
    - "http://localhost"
    - "http://erp-frontend:3000"
  enable_compression: false
  compression_level: 0

# Health Check Optimization
health:
  cache_timeout: "60s"        # Cache health status for 60 seconds (increased from 30s)
  check_interval: "120s"      # Background checks every 2 minutes (increased from 60s)
  max_concurrent_checks: 2    # Max 2 concurrent health checks (reduced from 3)
  http_timeout: "10s"         # HTTP health check timeout (increased from 5s)

jwt:
  secret: "your-super-secret-jwt-key-change-in-production"  # Shared secret for HS256
  public_key_path: ""  # Path to RSA public key file (not used with HS256)
  jwks_url: "http://auth-service:8080/api/v1/.well-known/jwks.json"  # JWKS endpoint URL (not used with HS256)
  cache_ttl: "1h"
  algorithm: "HS256"
  issuer: "erp-auth-service"

logging:
  level: "warn"  # debug, info, warn, error, fatal - Reduced from info to warn
  format: "json"  # json, text
  output: "stdout"  # stdout, stderr, file
  buffer_size: 500  # Reduced from 1000 to 500
  flush_interval: "10s"  # Increased from 5s to 10s
  elasticsearch:
    urls:
      - "http://elasticsearch:9200"
    username: ""
    password: ""
    index_name: "go-api-gateway-logs"