server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  shutdown_timeout: "10s"
  cors:
    allowed_origins:
      - "http://localhost:3000"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "Authorization"
      - "Content-Type"
    allow_credentials: true
    max_age: 86400

database:
  host: "localhost"
  port: 5432
  name: "test_db"
  user: "test_user"
  password: "test_pass"
  ssl_mode: "disable"

redis:
  host: "localhost"
  port: 6379
  db: 0
  pool_size: 10

kafka:
  brokers:
    - "localhost:9092"
  client_id: "test-gateway"

grpc:
  auth_service:
    host: "localhost"
    port: 50051
  crm_service:
    host: "localhost"
    port: 50052
  hrm_service:
    host: "localhost"
    port: 50053
  finance_service:
    host: "localhost"
    port: 50054

jwt:
  algorithm: "RS256"
  cache_ttl: "1h"
  issuer: "test-auth-service"

logging:
  level: "info"
  format: "json"
  output: "stdout"
  elasticsearch:
    urls:
      - "http://localhost:9200"
    index_name: "test-logs"

websocket:
  read_buffer_size: 4096
  write_buffer_size: 4096
  max_connections: 1000